/** Danh sách ngân hàng Việt Nam gợi ý sẵn cho form STK */
export const VIETNAM_BANKS = [
  'Vietcombank (VCB)',
  'VietinBank',
  'BIDV',
  'Agribank',
  'Techcombank (TCB)',
  'MB Bank',
  'ACB',
  'VPBank',
  'TPBank',
  'Sacombank',
  'HDBank',
  'VIB',
  'SHB',
  'SeABank',
  'MSB',
  'OCB',
  'LPBank',
  'Eximbank',
  'PVcomBank',
  'Bac A Bank',
  'Nam A Bank',
  'ABBANK',
  'VietABank',
  'NCB',
  'BaoViet Bank',
  'KienlongBank',
  'Saigonbank',
  'PG Bank',
  'DongA Bank',
  'CB Bank',
  'Woori Bank',
  'Shinhan Bank',
  'Hong Leong Bank',
  'Public Bank Vietnam',
  'UOB Vietnam',
  'CIMB Vietnam',
  'HSBC Vietnam',
  'Standard Chartered Vietnam'
];
